# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
jobs:
  build:
    machine: true # uses default image

    steps:
      - add_ssh_keys:
          fingerprints:
            - "f1:98:91:1c:d9:7c:5e:52:3c:20:26:e0:1c:10:4b:4c"

      - run: ssh ubuntu@52.221.186.212 'pwd' | 'touch 2.log'
      - run: echo "hello world"


